### ISSUE TITLE
.bash_profile issue

### ISSUE THREAD

**Issue by ritch** [strongloop/loopback-oracle-installer#1]
When running the installer my .profile no longer loads. In iterm (osx app) I can repro this with these steps...
- Double check my .profile is loaded by looking at the prompt (setting from my .profile)
- Run the installer
- Open a new tab
- Prompt is default, no aliases or other settings available from .profile

If I reopen iterm, everything seems to work so I am not sure the exact location of the issue. Maybe the installer is running `source .bash_profile` or something similar?

**Comment by loay** [comment]
Hi @ritch 
Is this issue resolved? Can I close it?
Thanks.

**Comment by dhmlau** [comment]
Since this issue was last updated more than 2 years, I'd like to close it due to inactivity.
