### ISSUE TITLE
Cannot install loopback-oracle-installer on windows node 6.4.0 loopback-oracle-Windows-x64-abi48-1.8.0.tar.gz not found

### ISSUE THREAD

**Issue by pawel-pohorski** [strongloop/loopback-oracle-installer#14]
Downloading/Extracting http://7e9918db41dd01dbf98e-ec15952f71452bc0809d79c86f5751b6.r22.cf1.rackcdn.com/loopback-oracle-
Windows-x64-abi48-1.8.0.tar.gz
HTTP proxy: http://webproxy.usq.edu.au:8080/
Error: Prebuilt tarball not found for your node version and platform: http://7e9918db41dd01dbf98e-ec15952f71452bc0809d79
c86f5751b6.r22.cf1.rackcdn.com/loopback-oracle-Windows-x64-abi48-1.8.0.tar.gz
    at Request.<anonymous> (F:\Software Projects\USQ\uconnect-api-layer-internal\node_modules\loopback-connector-oracle\
node_modules\loopback-oracle-installer\lib\download.js:83:24)
    at emitOne (events.js:96:13)
    at Request.emit (events.js:188:7)
    at Request.onRequestResponse (F:\Software Projects\USQ\uconnect-api-layer-internal\node_modules\request\request.js:9
54:10)
    at emitOne (events.js:96:13)
    at ClientRequest.emit (events.js:188:7)
    at HTTPParser.parserOnIncomingClient [as onIncoming](_http_client.js:472:21)
    at HTTPParser.parserOnHeadersComplete (_http_common.js:105:23)
    at Socket.socketOnData (_http_client.js:361:20)
    at emitOne (events.js:96:13)
npm WARN cldrjs@0.4.4 requires a peer of cldr-data@>=25 but none was installed.
npm WARN globalize@1.1.1 requires a peer of cldr-data@>=25 but none was installed.
npm WARN usq-mobile-api-layer-internal@0.0.1 No description
npm WARN usq-mobile-api-layer-internal@0.0.1 No license field.
npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\Program Files\nodejs\node.exe" "C:\Users\u1036732\AppData\Roaming\npm\node_modules\npm\bin\
\npm-cli.js" "install"
npm ERR! node v6.4.0
npm ERR! npm  v3.10.6
npm ERR! code ELIFECYCLE

npm ERR! loopback-oracle-installer@1.4.6 install: `node pkginstall.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the loopback-oracle-installer@1.4.6 install script 'node pkginstall.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the loopback-oracle-installer package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node pkginstall.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs loopback-oracle-installer
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls loopback-oracle-installer
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:

**Comment by petyhaker** [comment]
I am having the same problem. 
Only difference is I am using node 7.0.0 & npm v3.10.8. 
Any ideas?

**Comment by sidhukad** [comment]
I had a similar error while npm update. Any solutions for this?

**Comment by raymondfeng** [comment]
Please use loopback-connector-oracle@3.x instead.

**Comment by sidhukad** [comment]
Thanks, but I can't get it working

`> loopback-oracle-installer@3.0.0 install /Users/siddhartha.kadiyala/workspace/BridgeNow-API Server/node_modules/loopback-oracle-installer
> node pkginstall.js

Installation values -> oracledb location: /Users/siddhartha.kadiyala/workspace/BridgeNow-API Server/node_modules/loopback-connector-oracle/node_modules Prepackaged tarball url: http://7e9918db41dd01dbf98e-ec15952f71452bc0809d79c86f5751b6.r22.cf1.rackcdn.com  oracleversion: 2.0.0 oracledbmodule: oracledb@^1.11.0

Downloading/Extracting http://7e9918db41dd01dbf98e-ec15952f71452bc0809d79c86f5751b6.r22.cf1.rackcdn.com/loopback-oracle-MacOSX-x64-abi48-2.0.0.tar.gz

JadeConnector@1.0.0 /Users/siddhartha.kadiyala/workspace/BridgeNow-API Server
└── (empty)

npm WARN JadeConnector@1.0.0 No license field.
npm ERR! Darwin 16.3.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "update"
npm ERR! node v6.9.5
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE

npm ERR! loopback-oracle-installer@3.0.0 install: `node pkginstall.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the loopback-oracle-installer@3.0.0 install script 'node pkginstall.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the loopback-oracle-installer package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node pkginstall.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs loopback-oracle-installer
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls loopback-oracle-installer
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/siddhartha.kadiyala/workspace/BridgeNow-API Server/npm-debug.log
npm ERR! code 1`

**Comment by lakamsani** [comment]
The correct URL is this: http://7e9918db41dd01dbf98e-ec15952f71452bc0809d79c86f5751b6.r22.cf1.rackcdn.com/loopback-oracle-MacOSX-x64-1.5.0.tar.gz . How can we make npm install to use that instead of the non-existent http://7e9918db41dd01dbf98e-ec15952f71452bc0809d79c86f5751b6.r22.cf1.rackcdn.com/loopback-oracle-MacOSX-x64-abi57-2.1.0.tar.gz?

**Comment by lakamsani** [comment]
I was able to move forward on this one after ensuring that instant client is correctly installed and OC_LIB_DIR and OCI_LIB_DIR are correctly set (details here: https://github.com/oracle/node-oracledb as listed in the warning messages below). This is because when it fails to find that pre-built file it will try to build it locally. Here are the successful build logs on my Mac (Windows issue might be similar). 
```bash
kp-apic-oracle npm install loopback-connector-oracle --save

> loopback-oracle-installer@3.0.0 install /Users/vamsee/Development/kp/kp-apic-oracle/node_modules/loopback-oracle-installer
> node pkginstall.js

Installation values -> oracledb location: /Users/vamsee/Development/kp/kp-apic-oracle/node_modules/loopback-connector-oracle/node_modules Prepackaged tarball url: http://7e9918db41dd01dbf98e-ec15952f71452bc0809d79c86f5751b6.r22.cf1.rackcdn.com  oracleversion: 2.1.0 oracledbmodule: oracledb@^1.13.0

Downloading/Extracting http://7e9918db41dd01dbf98e-ec15952f71452bc0809d79c86f5751b6.r22.cf1.rackcdn.com/loopback-oracle-MacOSX-x64-abi57-2.1.0.tar.gz

Pre-packaged file http://7e9918db41dd01dbf98e-ec15952f71452bc0809d79c86f5751b6.r22.cf1.rackcdn.com/loopback-oracle-MacOSX-x64-abi57-2.1.0.tar.gz doesn't exist. Checking if user has installed pre-requisites offline as per instructions in https://github.com/oracle/node-oracledb/blob/master/INSTALL.md

Attempting to install oracledb@^1.13.0 node module under /Users/vamsee/Development/kp/kp-apic-oracle/node_modules/loopback-connector-oracle/node_modules. If the installation fails with errors, please install pre-requisites for oracledb offline as per https://github.com/oracle/node-oracledb/blob/master/INSTALL.md and retry installing loopback-oracle-connector.

Found Oracledb pre-requisites...
Installed Oracledb node module successfully.

> oracledb@1.13.1 install /Users/vamsee/Development/kp/kp-apic-oracle/node_modules/loopback-connector-oracle/node_modules/oracledb
> node-gyp rebuild

  CXX(target) Release/obj.target/oracledb/src/njs/src/njsOracle.o
  CXX(target) Release/obj.target/oracledb/src/njs/src/njsPool.o
  CXX(target) Release/obj.target/oracledb/src/njs/src/njsConnection.o
  CXX(target) Release/obj.target/oracledb/src/njs/src/njsResultSet.o
  CXX(target) Release/obj.target/oracledb/src/njs/src/njsMessages.o
../src/njs/src/njsMessages.cpp:103:22: warning: passing an object that undergoes default argument promotion to 'va_start' has undefined
      behavior [-Wvarargs]
    va_start (vlist, err);
                     ^
../src/njs/src/njsMessages.cpp:94:48: note: parameter of type 'NJSErrorType' is declared here
string NJSMessages::getErrorMsg ( NJSErrorType err, ... )
                                               ^
1 warning generated.
  CXX(target) Release/obj.target/oracledb/src/njs/src/njsIntLob.o
../src/njs/src/njsIntLob.cpp:1711:3: warning: cannot refer to a non-static member from the handler of a constructor function try block
      [-Wexceptions]
  cleanup();
  ^
1 warning generated.
  CXX(target) Release/obj.target/oracledb/src/dpi/src/dpiEnv.o
  CXX(target) Release/obj.target/oracledb/src/dpi/src/dpiEnvImpl.o
../src/dpi/src/dpiEnvImpl.cpp:117:3: warning: cannot refer to a non-static member from the handler of a constructor function try block
      [-Wexceptions]
  cleanup();
  ^
1 warning generated.
  CXX(target) Release/obj.target/oracledb/src/dpi/src/dpiException.o
  CXX(target) Release/obj.target/oracledb/src/dpi/src/dpiExceptionImpl.o
  CXX(target) Release/obj.target/oracledb/src/dpi/src/dpiConnImpl.o
../src/dpi/src/dpiConnImpl.cpp:111:3: warning: cannot refer to a non-static member from the handler of a constructor function try block
      [-Wexceptions]
  cleanup();
  ^
../src/dpi/src/dpiConnImpl.cpp:164:3: warning: cannot refer to a non-static member from the handler of a constructor function try block
      [-Wexceptions]
  cleanup ();
  ^
In file included from ../src/dpi/src/dpiConnImpl.cpp:28:
../src/dpi/src/dpiConnImpl.h:194:16: warning: private field 'pingInterval_' is not used [-Wunused-private-field]
  int          pingInterval_;   // Time to elapse before checking for aliveness
               ^
../src/dpi/src/dpiConnImpl.h:195:17: warning: private field 'lasttick_' is not used [-Wunused-private-field]
  long         *lasttick_;      // next ping time if time elapsed.
                ^
4 warnings generated.
  CXX(target) Release/obj.target/oracledb/src/dpi/src/dpiDateTimeArrayImpl.o
  CXX(target) Release/obj.target/oracledb/src/dpi/src/dpiPoolImpl.o
../src/dpi/src/dpiPoolImpl.cpp:154:3: warning: cannot refer to a non-static member from the handler of a constructor function try block
      [-Wexceptions]
  cleanup();
  ^
1 warning generated.
  CXX(target) Release/obj.target/oracledb/src/dpi/src/dpiStmtImpl.o
../src/dpi/src/dpiStmtImpl.cpp:120:3: warning: cannot refer to a non-static member from the handler of a constructor function try block
      [-Wexceptions]
  cleanup ();
  ^
1 warning generated.
  CXX(target) Release/obj.target/oracledb/src/dpi/src/dpiUtils.o
  CXX(target) Release/obj.target/oracledb/src/dpi/src/dpiLob.o
  CXX(target) Release/obj.target/oracledb/src/dpi/src/dpiCommon.o
  SOLINK_MODULE(target) Release/oracledb.node
npm notice created a lockfile as package-lock.json. You should commit this file.
+ oracledb@1.13.1
added 93 packages in 21.428s
+ loopback-connector-oracle@3.2.0
added 18 packages in 29.682s
```

**Comment by raymondfeng** [comment]
A better way to install the oracle connector is as follows:

```
1. npm i -g loopback-cli
2. cd <your-app>
3. lb oracle
```

**Comment by dhmlau** [comment]
Closing as resolved.  Feel free to reopen if this is still an issue.  Thanks.
