### ISSUE TITLE
MacOS 10.11.6 node 4.4.7 Throws errors for prebuilt tarball

### ISSUE THREAD

**Issue by signalsanty** [strongloop/loopback-oracle-installer#21]
### Bug or feature request

- [x ] Bug
- [ ] Feature request

### Description of feature (or steps to reproduce if bug)

Downloading/Extracting http://7e9918db41dd01dbf98e-ec15952f71452bc0809d79c86f5751b6.r22.cf1.rackcdn.com/loopback-oracle-MacOSX-x64-abi46-1.5.0.tar.gz
[Error: Prebuilt tarball not found for your node version and platform: http://7e9918db41dd01dbf98e-ec15952f71452bc0809d79c86f5751b6.r22.cf1.rackcdn.com/loopback-oracle-MacOSX-x64-abi46-1.5.0.tar.gz]

### Expected result
Please rebuild and upload

**Comment by raymondfeng** [comment]
Please upgrade to loopback-connector-oracle@3.x

**Comment by signalsanty** [comment]
thanks
